title: "Satoshi Matsuzawa's Academic Website"
description: "Personal website for Satoshi Matsuzawa, an independent scholar in economic development and economic history."
url: "https://satoshimatsuzawa.github.io"
baseurl: ""
author: "Satoshi Matsuzawa"
email: "satoshi.matsuzawa.g@gmail.com"  # Add your email here
